global:
  scrape_interval: 5s
  external_labels:
    monitor: "prometheus_monitor"

rule_files:
  # write rules later

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

#   - job_name: cadvisor
#     static_configs:
#       - targets: ["cadvisor:9092"]